### ISSUE TITLE
Windows selection

### ISSUE THREAD

**Issue by thangngoc89** [samleoqh/Viola-Unet#6]
I'm curious how did you choose the 3 windows for RGB style data input? 
I can see that the windows level changed between v1 and v2, is this because of dataset changes? If so, how did you calculate these window values? 

V1 window: `wind_levels = [[0,100], [-15, 200],[-100, 1300]]`
V2 window: `wind_levels = [[15,85], [-15, 200],[-100, 1300]]`

**Comment by samleoqh** [comment]
The idea comes from  [1st Place Solution of RSNA Intracranial Hemorrhage Detection](https://www.kaggle.com/competitions/rsna-intracranial-hemorrhage-detection/discussion/117210), but we used a slightly different windowing levels on V1 guided by our training experiments. 
For V2, we changed the first window value based on our statistics analysis on the extended datasets using the percentiles 0.05 and 99.5 of foreground image intensities.

**Comment by thangngoc89** [comment]
I see. Thank you for your response and keep up the good works.
